# Generated by Django 5.0.6 on 2025-06-29 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(max_length=50)),
                ('duracion_semanas', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cupos_disponibles', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='cursos/fotos')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_certificado', models.BooleanField(default=False)),
                ('profesor', models.CharField(max_length=100, verbose_name='Profesor asignado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
