# Generated by Django 5.0.6 on 2025-07-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='titulo',
        ),
    ]
